// AUTO-GENERATED by LanguageGameTool. Do not modify.

// Uses particle texture files found in F:\MNECreationsSVN\src\WindowsPhone\LanguageGameWp8Dx\LanguageGameWp8Dx\LanguageGameWp8Dx\Assets\Particles\*.dds

#pragma once

namespace LanguageGameWp8DxComponent
{

	public enum class ParticleEffect
	{
		bubble,
		dot01,
		fire,
		firework,
		flash,
		flash01,
		flower01,
		fly,
		glow,
		halo,
		light,
		orbask01,
		orbask02,
		orbask03,
		orbcollect01,
		orbcollect02,
		orbcollect03,
		orbcollect03_key,
		orbhunt01,
		orbhunt02,
		orbhunt04,
		orbhunt04_key,
		orbreflect01,
		orbreflect02,
		orbreflect04,
		rain04,
		rain05,
		rain07,
		smoke,
		smoke02,
		smoke03,
		smoke05,
		snow,
		star03,
		swirl,
		swirl01,
		swirl02,
		wind,

		NumOfEffects
	};

	public ref class ParticleEffectEnum sealed
	{
	public:
		property ParticleEffect EffectId
		{
			ParticleEffect  get()
			{
				return m_effectId;
			}
		}

	private:
		ParticleEffect m_effectId;
	};
}

static const wchar_t * PARTICLE_TEXTURES[] =
{
	L"Assets\\Particles\\bubble.dds",
	L"Assets\\Particles\\dot01.dds",
	L"Assets\\Particles\\fire.dds",
	L"Assets\\Particles\\firework.dds",
	L"Assets\\Particles\\flash.dds",
	L"Assets\\Particles\\flash01.dds",
	L"Assets\\Particles\\flower01.dds",
	L"Assets\\Particles\\fly.dds",
	L"Assets\\Particles\\glow.dds",
	L"Assets\\Particles\\halo.dds",
	L"Assets\\Particles\\light.dds",
	L"Assets\\Particles\\orbask01.dds",
	L"Assets\\Particles\\orbask02.dds",
	L"Assets\\Particles\\orbask03.dds",
	L"Assets\\Particles\\orbcollect01.dds",
	L"Assets\\Particles\\orbcollect02.dds",
	L"Assets\\Particles\\orbcollect03.dds",
	L"Assets\\Particles\\orbcollect03_key.dds",
	L"Assets\\Particles\\orbhunt01.dds",
	L"Assets\\Particles\\orbhunt02.dds",
	L"Assets\\Particles\\orbhunt04.dds",
	L"Assets\\Particles\\orbhunt04_key.dds",
	L"Assets\\Particles\\orbreflect01.dds",
	L"Assets\\Particles\\orbreflect02.dds",
	L"Assets\\Particles\\orbreflect04.dds",
	L"Assets\\Particles\\rain04.dds",
	L"Assets\\Particles\\rain05.dds",
	L"Assets\\Particles\\rain07.dds",
	L"Assets\\Particles\\smoke.dds",
	L"Assets\\Particles\\smoke02.dds",
	L"Assets\\Particles\\smoke03.dds",
	L"Assets\\Particles\\smoke05.dds",
	L"Assets\\Particles\\snow.dds",
	L"Assets\\Particles\\star03.dds",
	L"Assets\\Particles\\swirl.dds",
	L"Assets\\Particles\\swirl01.dds",
	L"Assets\\Particles\\swirl02.dds",
	L"Assets\\Particles\\wind.dds",
};